### PR TITLE
feat: add `import` of config files and introduce color theme

### PR DESCRIPTION
**Pull request by JarKz**
# Motivation

At begin of development of the application there was not complex configuration, just simple and single TOML file. But since we feeding this application by coolest features, the config file becomes very complex.

To simplify this process, need to separate single config file into smaller. And I begin from colors.

## Breaking changes

I decided that we shouldn't save backward compatibility in this case because we aim to simplicity. So previous config values will be deprecated and removed from parsing.

Also there is other breaking change - I've moved the `font_size` property (previously unnamed) from `general.font` into `TextProperty`. It is more convenient and logic to use font size per text field instead of using global font size.

## TODO

- [X] - group colors into `Theme` structure
- [X] - move `font_size` into `TextProperty`
- [x] - implement `import` of config files in TOML's root table
- [x] - update documentation

### CODE REVIEW

**Comment by JarKz** [comment]
Well, it's not the best idea. I'll continue work on this to make `imports` or `include` instead of files at the fixed path.

So I've converted it into draft. Now I'll rename the title to correct name.

**Comment by JarKz** [comment]
# Config importing

Now #33 also solved. For this uses `use` keyword for importing.

## Syntax

The import statement should be a top of TOML file, in root table (before any table definition), and accepts only array of strings that are paths to config file. Currently only environment and tilde expansion are supported. The relative path expansion is not supported yet.

Example:
```toml
use = [
  "path/to/other/cfg/File.toml",
  "$ENV/OtherFile.toml",
  "~/.config/noti/ThirdFile.toml",
]
```

## Priority

Imagine that the imported configuration from other file is *injected* to main config file. If you define the config value from other file (e.g. `display.padding = 20`) and in main config you also define the SAME config variable with different value (e.g. `display.padding = 15`). The upper value will not be taken because it was **overriden** by value that placed lower.

So, the main config file is more prior that other config file and it is same for them (i.e. the other file is more prior that an imported config file in it).

## What about theming?

As I described in previous message, it is better to use config importing instead of looking up the theme file from specific path. So themes are moved into config files as array. Now they have such syntax:

```toml
[[theme]]
name = "my-theme-name"

[theme.low]
foreground = "#000"
background = "#FFF"
border = "#000"

# The same syntax for theme.normal and theme.critical
```

The theme's name is important value because by it correct theme will be set, otherwise the default theme will be used. To select theme, enough use `display.theme`:

```toml
[display]
theme = "my-theme-name"
```

And it is also applicable to configuration per application.

**Comment by JarKz** [comment]
And, need to update documentation before merging.

**Review by jsonmaf1a — APPROVED** [review]

**Review by vlinearo — APPROVED** [review]
Sigma code

**Pull request merged**
